// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SICAF.Data.Context;

#nullable disable

namespace SICAF.Data.Migrations
{
    [DbContext(typeof(SicafDbContext))]
    [Migration("20251110151209_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SICAF.Data.Entities.Academic.Aircraft", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador único de la entidad");

                    b.Property<string>("AircraftType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Tipo de aeronave: AVION o HELICOPTERO");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indica si la entidad ha sido eliminada lógicamente (soft delete)");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Matrícula de la aeronave sin guiones");

                    b.Property<double>("TotalFlightHours")
                        .HasColumnType("float")
                        .HasComment("Horas totales de vuelo");

                    b.Property<string>("WingType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Tipo de ala: FIXED_WING o ROTARY_WING");

                    b.HasKey("Id");

                    b.HasIndex("AircraftType")
                        .HasDatabaseName("IX_Aircrafts_AircraftType");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Aircraft_IsDeleted");

                    b.HasIndex("WingType")
                        .HasDatabaseName("IX_Aircrafts_WingType");

                    b.HasIndex("Registration", "WingType")
                        .IsUnique()
                        .HasDatabaseName("IX_Aircrafts_Registration_WingType_Unique")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Aircrafts", null, t =>
                        {
                            t.HasCheckConstraint("CK_Aircrafts_WingType", "[WingType] IN ('FIJA', 'ROTATORIA')");
                        });
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.AviationProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador único de la entidad");

                    b.Property<string>("FlightPosition")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasComment("Posición de vuelo");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indica si la entidad ha sido eliminada lógicamente (soft delete)");

                    b.Property<string>("PID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("PID del piloto");

                    b.Property<double>("TotalFlightHours")
                        .HasColumnType("float")
                        .HasComment("Horas totales de vuelo");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID del usuario");

                    b.Property<string>("WingType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Tipo de ala de la aeronave");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_AviationProfile_IsDeleted");

                    b.HasIndex("PID")
                        .IsUnique()
                        .HasDatabaseName("IX_AviationProfiles_PID_Unique");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_AviationProfiles_UserId");

                    b.HasIndex("WingType")
                        .HasDatabaseName("IX_AviationProfiles_WingType");

                    b.ToTable("AviationProfiles", (string)null);
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador único de la entidad");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Nombre del curso");

                    b.Property<int>("CourseNumber")
                        .HasMaxLength(3)
                        .HasColumnType("int")
                        .HasComment("Número del curso (máximo 3 dígitos)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Descripción del curso");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de finalización del curso");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indica si la entidad ha sido eliminada lógicamente (soft delete)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de inicio del curso");

                    b.HasKey("Id");

                    b.HasIndex("CourseName")
                        .HasDatabaseName("IX_Courses_CourseName");

                    b.HasIndex("CourseNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Courses_CourseNumber_Unique")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Course_IsDeleted");

                    b.HasIndex("StartDate", "EndDate")
                        .HasDatabaseName("IX_Courses_Dates");

                    b.ToTable("Courses", null, t =>
                        {
                            t.HasCheckConstraint("CK_Courses_CourseNumber", "CourseNumber >= 1 AND CourseNumber <= 999");
                        });
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.FlightHourLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador único de la entidad");

                    b.Property<Guid>("AircraftId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID de la aeronave utilizada");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID del curso");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha del registro");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indica si la entidad ha sido eliminada lógicamente (soft delete)");

                    b.Property<double>("MachineFlightHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)")
                        .HasComment("Horas de vuelo registrada en la aeronave");

                    b.Property<double>("ManFlightHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)")
                        .HasComment("Horas de vuelo registrada para el hombre (MachineFlightHours x 1.3)");

                    b.Property<Guid?>("MissionId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID de la misión (nullable para misiones no evaluables)");

                    b.Property<Guid?>("NonEvaluableMissionId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID de la misión no evaluable (nullable para misiones evaluables)");

                    b.Property<string>("Observations")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Observaciones adicionales");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Rol del usuario: Estudiante, Instructor");

                    b.Property<double>("SilaboFlightHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)")
                        .HasComment("Horas de vuelo en semana");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID del usuario");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId")
                        .HasDatabaseName("IX_FlightHourLogs_AircraftId");

                    b.HasIndex("CourseId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_FlightHourLog_IsDeleted");

                    b.HasIndex("MissionId");

                    b.HasIndex("NonEvaluableMissionId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_FlightHourLogs_UserId");

                    b.ToTable("FlightHourLogs", (string)null);
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.Mission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador único de la entidad");

                    b.Property<double>("FlightHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)")
                        .HasComment("Horas de vuelo requeridas para la misión");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indica si la entidad ha sido eliminada lógicamente (soft delete)");

                    b.Property<int>("MissionNumber")
                        .HasColumnType("int")
                        .HasComment("Número secuencial de la misión (1-85)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Nombre de la misión");

                    b.Property<Guid>("PhaseId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID de la fase");

                    b.Property<string>("WingType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Tipo de ala: FIJA o ROTATORIA");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Mission_IsDeleted");

                    b.HasIndex("MissionNumber")
                        .HasDatabaseName("IX_Missions_MissionNumber");

                    b.HasIndex("WingType")
                        .HasDatabaseName("IX_Missions_WingType");

                    b.HasIndex("PhaseId", "MissionNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Missions_PhaseId_MissionNumber_Unique")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("Missions", (string)null);
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.MissionTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador único de la entidad");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("Orden de visualización");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indica si la entidad ha sido eliminada lógicamente (soft delete)");

                    b.Property<bool>("IsP3Task")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indica si esta tarea es P3 (crítica) en esta misión");

                    b.Property<Guid>("MissionId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID de la misión");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID de la tarea");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_MissionTask_IsDeleted");

                    b.HasIndex("IsP3Task")
                        .HasDatabaseName("IX_MissionTasks_IsP3Task");

                    b.HasIndex("MissionId")
                        .HasDatabaseName("IX_MissionTasks_MissionId");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("IX_MissionTasks_TaskId");

                    b.ToTable("MissionTasks", (string)null);
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.NonEvaluableGradeReason", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador único de la entidad");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha del registro del motivo");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indica si la entidad ha sido eliminada lógicamente (soft delete)");

                    b.Property<Guid>("NonEvaluableTaskGradeId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID de la calificación de tarea no evaluable");

                    b.Property<string>("ReasonCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Categoría: Mental, Fisica, Emocional");

                    b.Property<string>("ReasonDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Descripción o motivo de la calificación N (No Satisfactorio)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_NonEvaluableGradeReason_IsDeleted");

                    b.HasIndex("NonEvaluableTaskGradeId")
                        .HasDatabaseName("IX_NonEvaluableGradeReasons_NonEvaluableTaskGradeId");

                    b.HasIndex("ReasonCategory")
                        .HasDatabaseName("IX_NonEvaluableGradeReasons_ReasonCategory");

                    b.ToTable("NonEvaluableGradeReasons", (string)null);
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.NonEvaluableMissionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador único de la entidad");

                    b.Property<Guid>("AircraftId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID de la aeronave utilizada en la misión");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID del curso");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de realización de la misión no evaluable");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID del usuario con rol de instructor");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indica si la entidad ha sido eliminada lógicamente (soft delete)");

                    b.Property<double>("MachineFlightHours")
                        .HasColumnType("float")
                        .HasComment("Horas de vuelo máquina");

                    b.Property<double>("ManFlightHours")
                        .HasColumnType("float")
                        .HasComment("Horas de vuelo máquina");

                    b.Property<int>("NonEvaluableMissionNumber")
                        .HasColumnType("int")
                        .HasComment("Número de misión no evaluable (1, 2, 3, etc. para MNE1, MNE2, MNE3...)");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasComment("Observaciones generales de la misión no evaluable");

                    b.Property<Guid>("PhaseId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID de la fase");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID del usuario con rol de estudiante");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId")
                        .HasDatabaseName("IX_NonEvaluableMissionRecords_AircraftId");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("IX_NonEvaluableMissionRecords_CourseId");

                    b.HasIndex("InstructorId")
                        .HasDatabaseName("IX_NonEvaluableMissionRecords_InstructorId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_NonEvaluableMissionRecord_IsDeleted");

                    b.HasIndex("PhaseId")
                        .HasDatabaseName("IX_NonEvaluableMissionRecords_PhaseId");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("IX_NonEvaluableMissionRecords_StudentId");

                    b.HasIndex("StudentId", "CourseId", "NonEvaluableMissionNumber", "PhaseId")
                        .IsUnique()
                        .HasDatabaseName("IX_NonEvaluableMissionRecords_Student_Course_Phase_Number_Unique")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("NonEvaluableMissionRecords", (string)null);
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.NonEvaluableTaskGrade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador único de la entidad");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de la calificación");

                    b.Property<int>("EditCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("Contador de ediciones (máximo 2)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("Calificación: A, B, C, N, DM, SC (NO permite NR - N-Roja)");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID del usuario con rol de instructor");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indica si la entidad ha sido eliminada lógicamente (soft delete)");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de la última edición");

                    b.Property<Guid>("NonEvaluableMissionRecordId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID del registro de misión no evaluable");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID del usuario con rol de estudiante");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID de la tarea");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId")
                        .HasDatabaseName("IX_NonEvaluableTaskGrades_InstructorId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_NonEvaluableTaskGrade_IsDeleted");

                    b.HasIndex("NonEvaluableMissionRecordId")
                        .HasDatabaseName("IX_NonEvaluableTaskGrades_NonEvaluableMissionRecordId");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("IX_NonEvaluableTaskGrades_StudentId");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("IX_NonEvaluableTaskGrades_TaskId");

                    b.ToTable("NonEvaluableTaskGrades", (string)null);
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.Phase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador único de la entidad");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indica si la entidad ha sido eliminada lógicamente (soft delete)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Nombre de la fase");

                    b.Property<int>("PhaseNumber")
                        .HasColumnType("int")
                        .HasComment("Número de fase (secuencial)");

                    b.Property<Guid?>("PrerequisitePhaseId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID de la fase prerrequisito");

                    b.Property<int>("TotalMissions")
                        .HasColumnType("int")
                        .HasComment("Total de misiones de la fase");

                    b.Property<string>("WingType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Tipo de ala: FIJA o ROTATORIA");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Phase_IsDeleted");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Phase_Name");

                    b.HasIndex("PhaseNumber")
                        .HasDatabaseName("IX_Phase_PhaseNumber");

                    b.HasIndex("PrerequisitePhaseId")
                        .HasDatabaseName("IX_Phase_PrerequisitePhaseId");

                    b.HasIndex("WingType")
                        .HasDatabaseName("IX_Phases_WingType");

                    b.HasIndex("PhaseNumber", "WingType")
                        .IsUnique()
                        .HasDatabaseName("IX_Phases_Number_WingType_Unique")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("Phases", (string)null);
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.StudentCommitteeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador único de la entidad");

                    b.Property<string>("ActaNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Número de acta");

                    b.Property<int>("CommitteeNumber")
                        .HasColumnType("int")
                        .HasComment("Número de veces en comite por fase");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID del curso");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime")
                        .HasComment("Fecha en que fue a comité (automático)");

                    b.Property<string>("Decision")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Decisión: continuar o suspender el curso");

                    b.Property<DateTime?>("DecisionDate")
                        .HasColumnType("datetime")
                        .HasComment("Fecha de la decisión");

                    b.Property<string>("DecisionObservations")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)")
                        .HasComment("Observaciones sobre la decisión");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indica si la entidad ha sido eliminada lógicamente (soft delete)");

                    b.Property<bool>("IsResolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indica si la misión fue resuelta");

                    b.Property<Guid?>("LeaderId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID del usuario con rol de lider de vuelo");

                    b.Property<Guid>("PhaseId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID de la fase");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Motivo de ir al comite");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID del usuario con rol de estudiante");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_StudentCommitteeRecord_IsDeleted");

                    b.HasIndex("IsResolved")
                        .HasDatabaseName("IX_StudentCommitteeRecords_IsResolved");

                    b.HasIndex("LeaderId");

                    b.HasIndex("PhaseId")
                        .HasDatabaseName("IX_StudentCommitteeRecords_PhaseId");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("IX_StudentCommitteeRecords_StudentId");

                    b.ToTable("StudentCommitteeRecords", (string)null);
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.StudentGradeNRedReason", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador único de la entidad");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha del motivo de la N-Roja");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indica si la entidad ha sido eliminada lógicamente (soft delete)");

                    b.Property<string>("ReasonCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Categoría: Mental, Fisica, Emocional");

                    b.Property<string>("ReasonDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Descripción o motivo de la N-Roja");

                    b.Property<Guid>("StudentTaskGradeId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID de la calificación del estudiante");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_StudentGradeNRedReason_IsDeleted");

                    b.HasIndex("ReasonCategory")
                        .HasDatabaseName("IX_StudentGradeNRedReason_ReasonCategory");

                    b.HasIndex("StudentTaskGradeId")
                        .HasDatabaseName("IX_StudentGradeNRedReason_StudentTaskGradeId");

                    b.ToTable("StudentGradeNRedReasons", (string)null);
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.StudentMissionProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador único de la entidad");

                    b.Property<Guid>("AircraftId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID de la aeronave utilizada en la misión");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID del curso");

                    b.Property<int>("CriticalFailures")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("Cantidad de fallas críticas (N-Rojas)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de realización de la misión");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID del usuario con rol de instructor");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indica si la entidad ha sido eliminada lógicamente (soft delete)");

                    b.Property<Guid>("MissionId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID de la misión");

                    b.Property<bool>("MissionPassed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indica si la misión fue aprobada");

                    b.Property<string>("Observations")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasComment("Observaciones adicionales");

                    b.Property<Guid>("PhaseId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID de la fase");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID del usuario con rol de estudiante");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId")
                        .HasDatabaseName("IX_StudentMissionProgress_AircraftId");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId")
                        .HasDatabaseName("IX_StudentMissionProgress_InstructorId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_StudentMissionProgress_IsDeleted");

                    b.HasIndex("MissionId")
                        .HasDatabaseName("IX_StudentMissionProgress_MissionId");

                    b.HasIndex("PhaseId")
                        .HasDatabaseName("IX_StudentMissionProgress_PhaseId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentMissionProgress", (string)null);
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.StudentPhaseProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador único de la entidad");

                    b.Property<int>("CompletedMissions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("Cantidad de misiones completadas");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID del curso");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de finalización de la fase");

                    b.Property<int>("FailedMissions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("Cantidad de misiones fallidas");

                    b.Property<bool>("IsCurrentPhase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Indica si es la fase actual del estudiante");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indica si la entidad ha sido eliminada lógicamente (soft delete)");

                    b.Property<bool>("IsSuspended")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indica si el estudiante está suspendido de la fase");

                    b.Property<Guid?>("LeaderId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID del usuario con participación de líder de vuelo");

                    b.Property<Guid?>("NextPhaseId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID de la fase siguiente");

                    b.Property<string>("Observations")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasComment("Observaciones");

                    b.Property<Guid>("PhaseId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID de la fase");

                    b.Property<bool>("PhasePassed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indica si el estudiante ha pasado la fase");

                    b.Property<Guid?>("PreviousPhaseId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID de la fase anterior");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de inicio de la fase");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Estado de la fase (EN PROCESO, COMPLETADA, FALLIDA, SUSPENDIDA)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID del usuario con rol de estudiante");

                    b.Property<DateTime?>("SuspensionDate")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de suspensión");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Razón de la suspensión");

                    b.HasKey("Id");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("IX_StudentPhaseProgress_CourseId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_StudentPhaseProgress_IsDeleted");

                    b.HasIndex("LeaderId")
                        .HasDatabaseName("IX_StudentPhaseProgress_LeaderId")
                        .HasFilter("[LeaderId] IS NOT NULL");

                    b.HasIndex("PhaseId")
                        .HasDatabaseName("IX_StudentPhaseProgress_PhaseId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_StudentPhaseProgress_Status");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("IX_StudentPhaseProgress_StudentId");

                    b.ToTable("StudentPhaseProgress", (string)null);
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.StudentTaskGrade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador único de la entidad");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de la calificación");

                    b.Property<int>("EditCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("Contador de ediciones");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("Calificación: A, B, C, N, NR (N ROJA)");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID del usuario con rol de Instructor");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indica si la entidad ha sido eliminada lógicamente (soft delete)");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de la ultima edición");

                    b.Property<Guid>("MissionId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID de la misión");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID del usuario con rol de estudiante");

                    b.Property<Guid>("StudentMissionProgressId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID del progreso de la misión del estudiante");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID de la tarea");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId")
                        .HasDatabaseName("IX_StudentTaskGrades_InstructorId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_StudentTaskGrade_IsDeleted");

                    b.HasIndex("MissionId");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("IX_StudentTaskGrades_StudentId");

                    b.HasIndex("StudentMissionProgressId");

                    b.HasIndex("TaskId");

                    b.ToTable("StudentTaskGrades", (string)null);
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.Tasks", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador único de la entidad");

                    b.Property<int>("Code")
                        .HasColumnType("int")
                        .HasComment("Código único de la tarea");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indica si la entidad ha sido eliminada lógicamente (soft delete)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasComment("Nombre descriptivo de la tarea");

                    b.Property<string>("WingType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Tipo de ala: FIJA o ROTATORIA");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Tasks_IsDeleted");

                    b.HasIndex("WingType")
                        .HasDatabaseName("IX_Tasks_WingType");

                    b.HasIndex("Code", "WingType")
                        .IsUnique()
                        .HasDatabaseName("IX_Tasks_Code_WingType_Unique")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.UserCourse", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador único de la entidad");

                    b.Property<DateTime>("AssignmentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Fecha de inscripción");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID del curso");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Indica si es la inscripción activa del estudiante");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indica si la entidad ha sido eliminada lógicamente (soft delete)");

                    b.Property<string>("ParticipationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Tipo de participación en el curso: ESTUDIANTE o INSTRUCTOR o LIDER DE VUELO");

                    b.Property<DateTime?>("UnassignmentDate")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de desactivación");

                    b.Property<string>("UnassignmentReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Razón de la desactivación");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID del usuario");

                    b.Property<string>("WingType")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Tipo de ala");

                    b.HasKey("Id");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("IX_UserCourses_CourseId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_UserCourses_IsActive");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_UserCourse_IsDeleted");

                    b.HasIndex("ParticipationType")
                        .HasDatabaseName("IX_UserCourses_ParticipationType");

                    b.HasIndex("UserId");

                    b.HasIndex("WingType")
                        .HasDatabaseName("IX_UserCourses_WingType");

                    b.ToTable("UserCourses", (string)null);
                });

            modelBuilder.Entity("SICAF.Data.Entities.Auditing.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador único de la entidad");

                    b.Property<string>("Action")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Acción ejecutada en el controlador");

                    b.Property<Guid?>("AffectedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID del usuario afectado por la operación");

                    b.Property<string>("AffectedUserIdentificationName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Identificación y nombre del usuario afectado por la operación");

                    b.Property<string>("Controller")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Controlador donde ocurre la operación");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha y hora de creación del registro");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador único de la entidad referenciada");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Nombre de la entidad sobre la cual se realiza la operación");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasComment("Dirección IP desde donde se realiza la operación");

                    b.Property<Guid?>("LoggedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID del usuario");

                    b.Property<string>("Module")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Módulo del sistema donde ocurre la operación");

                    b.Property<string>("NewValues")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasComment("Nuevos valores de la entidad en formato JSON");

                    b.Property<string>("OldValues")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasComment("Valores anteriores de la entidad en formato JSON");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Tipo de operación realizada (Create, Update, Delete, Read)");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Nombre de usuario");

                    b.Property<string>("UserRole")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Rol del usuario al momento de realizar la operación");

                    b.HasKey("Id");

                    b.HasIndex("AffectedUserId")
                        .HasDatabaseName("IX_AuditLogs_AffectedUserId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AuditLog_CreatedAt");

                    b.HasIndex("EntityId")
                        .HasDatabaseName("IX_AuditLogs_EntityId");

                    b.HasIndex("EntityName")
                        .HasDatabaseName("IX_AuditLogs_EntityName");

                    b.HasIndex("LoggedUserId")
                        .HasDatabaseName("IX_AuditLog_UserId");

                    b.HasIndex("OperationType")
                        .HasDatabaseName("IX_AuditLogs_OperationType");

                    b.HasIndex("EntityName", "EntityId")
                        .HasDatabaseName("IX_AuditLogs_EntityName_EntityId");

                    b.HasIndex("LoggedUserId", "AffectedUserId")
                        .HasDatabaseName("IX_AuditLogs_UserId_AffectedUserId");

                    b.HasIndex("LoggedUserId", "CreatedAt")
                        .HasDatabaseName("IX_AuditLog_UserId_CreatedAt");

                    b.HasIndex("EntityName", "OperationType", "CreatedAt")
                        .HasDatabaseName("IX_AuditLogs_EntityName_OperationType_CreatedAt");

                    b.HasIndex("Module", "Controller", "Action")
                        .HasDatabaseName("IX_AuditLog_Module_Controller_Action");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("SICAF.Data.Entities.Catalogs.MasterCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador único de la entidad");

                    b.Property<string>("CatalogType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("Código del catalogo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha de creación del registro");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Usuario que creo el registro");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Descripción del catalogo");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("Orden de visulización");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indica si la entidad ha sido eliminada lógicamente (soft delete)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Nombre del catalogo");

                    b.HasKey("Id");

                    b.HasIndex("CatalogType")
                        .HasDatabaseName("IX_MasterCatalogs_CatalogType");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_MasterCatalogs_Code_Unique");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("IX_MasterCatalogs_DisplayOrder");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_MasterCatalog_IsDeleted");

                    b.HasIndex("CatalogType", "Code")
                        .IsUnique()
                        .HasDatabaseName("IX_MasterCatalogs_Type_Code_Unique");

                    b.ToTable("MasterCatalogs", (string)null);
                });

            modelBuilder.Entity("SICAF.Data.Entities.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador único de la entidad");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Descripción del rol");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indica si la entidad ha sido eliminada lógicamente (soft delete)");

                    b.Property<bool>("IsSystemRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indica si el rol es un rol del sistema");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Nombre del rol");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Role_IsDeleted");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Roles_Name_Unique")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("SICAF.Data.Entities.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador único de la entidad");

                    b.Property<int>("AccessFailedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("Número de intentos fallidos de autenticación");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date")
                        .HasComment("Fecha de nacimiento del usuario");

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasComment("Factor RH de sangre (O+, O-, A+, A-, B+, B-, AB+, AB-)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("Tipo de documento de identificación (CC, CE, etc.)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Correo electrónico del usuario");

                    b.Property<string>("Force")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Fuerza a la que pertenece (Policía Nacional, Ejercito, etc.)");

                    b.Property<string>("Grade")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Grado policial del usuario");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Número del documento de identificación");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indica si la entidad ha sido eliminada lógicamente (soft delete)");

                    b.Property<bool>("IsPasswordSetByAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indica si la contraseña del usuario fue establecida por el administrador");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Apellidos del usuario");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime")
                        .HasComment("Fecha y hora hasta cuando el usuario está bloqueado");

                    b.Property<string>("LockoutReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Razón del bloqueo del usuario");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Nombres del usuario");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Colombia")
                        .HasComment("Nacionalidad del usuario");

                    b.Property<DateTime?>("PasswordChangeDate")
                        .HasColumnType("datetime")
                        .HasComment("Fecha y hora de cambio de contraseña del usuario");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Hash de la contraseña del usuario");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Número de teléfono del usuario");

                    b.Property<string>("PhotoContentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Tipo de contenido MIME de la fotografía");

                    b.Property<byte[]>("PhotoData")
                        .HasColumnType("varbinary(max)")
                        .HasComment("Fotografía del usuario en formato binario");

                    b.Property<string>("PhotoFileName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Nombre de archivo con la extensión");

                    b.Property<int?>("SeniorityOrder")
                        .HasColumnType("int")
                        .HasComment("Orden de antiguedad del usuario");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Nombre de usuario único para login");

                    b.HasKey("Id");

                    b.HasIndex("BirthDate")
                        .HasDatabaseName("IX_Users_BirthDate");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email_Unique")
                        .HasFilter("[Email] IS NOT NULL AND IsDeleted = 0");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_User_IsDeleted");

                    b.HasIndex("LockoutEnd")
                        .HasDatabaseName("IX_Users_LockoutEnd");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Username_Unique")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("DocumentType", "IdentificationNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Document_Unique")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("Grade", "SeniorityOrder")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Grade_SeniorityOrder_Unique")
                        .HasFilter("[Grade] IS NOT NULL AND [SeniorityOrder] IS NOT NULL AND IsDeleted = 0");

                    b.HasIndex("Name", "LastName")
                        .HasDatabaseName("IX_Users_FullName");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SICAF.Data.Entities.Identity.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador único de la entidad");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime")
                        .HasComment("Fecha de expiración del rol (para roles temporales)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indica si la entidad ha sido eliminada lógicamente (soft delete)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID del rol");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID del usuario");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_UserRoles_ExpiresAt");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_UserRole_IsDeleted");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_UserRoles_RoleId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserRoles_UserId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserRoles_User_Role_Unique")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("SICAF.Data.Entities.Logging.ErrorLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador único de la entidad");

                    b.Property<string>("Action")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Acción ejecutada en el controlador");

                    b.Property<string>("Controller")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Controlador donde ocurre la operación");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha y hora de creación del registro");

                    b.Property<string>("Environment")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Ambiente donde ocurrió el error (Development, Staging, Production)");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Tipo de excepción que se produjo");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("Método HTTP de la solicitud que causó el error");

                    b.Property<string>("InnerException")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasComment("Detalles de la excepción interna si existe");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasComment("Dirección IP desde donde se realiza la operación");

                    b.Property<bool>("IsResolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indica si el error ha sido resuelto");

                    b.Property<Guid?>("LoggedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ID del usuario");

                    b.Property<string>("MachineName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Nombre de la máquina donde ocurrió el error");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasComment("Mensaje descriptivo del error ocurrido");

                    b.Property<string>("Module")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Módulo del sistema donde ocurre la operación");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasComment("Notas sobre cómo se resolvió el error");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha y hora cuando se resolvió el error");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Usuario que marcó el error como resuelto");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Error")
                        .HasComment("Nivel de severidad del error");

                    b.Property<string>("StackTrace")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasComment("Stack trace completo del error para debugging");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int")
                        .HasComment("Código de estado HTTP asociado al error");

                    b.Property<string>("Url")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasComment("URL completa de la solicitud que generó el error");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Nombre de usuario");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_ErrorLog_CreatedAt");

                    b.HasIndex("Environment")
                        .HasDatabaseName("IX_ErrorLogs_Environment");

                    b.HasIndex("ExceptionType")
                        .HasDatabaseName("IX_ErrorLogs_ExceptionType");

                    b.HasIndex("IsResolved")
                        .HasDatabaseName("IX_ErrorLogs_IsResolved");

                    b.HasIndex("LoggedUserId")
                        .HasDatabaseName("IX_ErrorLog_UserId");

                    b.HasIndex("Severity")
                        .HasDatabaseName("IX_ErrorLogs_Severity");

                    b.HasIndex("StatusCode")
                        .HasDatabaseName("IX_ErrorLogs_StatusCode");

                    b.HasIndex("ExceptionType", "CreatedAt")
                        .HasDatabaseName("IX_ErrorLogs_ExceptionType_CreatedAt");

                    b.HasIndex("IsResolved", "ResolvedAt")
                        .HasDatabaseName("IX_ErrorLogs_IsResolved_ResolvedAt");

                    b.HasIndex("IsResolved", "Severity")
                        .HasDatabaseName("IX_ErrorLogs_IsResolved_Severity");

                    b.HasIndex("LoggedUserId", "CreatedAt")
                        .HasDatabaseName("IX_ErrorLog_UserId_CreatedAt");

                    b.HasIndex("Severity", "CreatedAt")
                        .HasDatabaseName("IX_ErrorLogs_Severity_CreatedAt");

                    b.HasIndex("LoggedUserId", "CreatedAt", "Severity")
                        .HasDatabaseName("IX_ErrorLogs_UserId_CreatedAt_Severity");

                    b.HasIndex("Module", "Controller", "Action")
                        .HasDatabaseName("IX_ErrorLog_Module_Controller_Action");

                    b.ToTable("ErrorLogs", (string)null);
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.AviationProfile", b =>
                {
                    b.HasOne("SICAF.Data.Entities.Identity.User", "User")
                        .WithOne("AviationProfile")
                        .HasForeignKey("SICAF.Data.Entities.Academic.AviationProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_AviationProfiles_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.FlightHourLog", b =>
                {
                    b.HasOne("SICAF.Data.Entities.Academic.Aircraft", "Aircraft")
                        .WithMany()
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FlightHourLogs_AircraftId");

                    b.HasOne("SICAF.Data.Entities.Academic.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FlightHourLogs_CourseId");

                    b.HasOne("SICAF.Data.Entities.Academic.Mission", "Mission")
                        .WithMany("FlightHourLogs")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_FlightHourLogs_MissionId");

                    b.HasOne("SICAF.Data.Entities.Academic.NonEvaluableMissionRecord", "NonEvaluableMission")
                        .WithMany()
                        .HasForeignKey("NonEvaluableMissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_FlightHourLogs_NonEvaluableMissionId");

                    b.HasOne("SICAF.Data.Entities.Identity.User", "User")
                        .WithMany("FlightHourLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FlightHourLogs_UserId");

                    b.Navigation("Aircraft");

                    b.Navigation("Course");

                    b.Navigation("Mission");

                    b.Navigation("NonEvaluableMission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.Mission", b =>
                {
                    b.HasOne("SICAF.Data.Entities.Academic.Phase", "Phase")
                        .WithMany("Missions")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Missions_PhaseId");

                    b.Navigation("Phase");
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.MissionTask", b =>
                {
                    b.HasOne("SICAF.Data.Entities.Academic.Mission", "Mission")
                        .WithMany("MissionTasks")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_MissionTasks_MissionId");

                    b.HasOne("SICAF.Data.Entities.Academic.Tasks", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_MissionTasks_TaskId");

                    b.Navigation("Mission");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.NonEvaluableGradeReason", b =>
                {
                    b.HasOne("SICAF.Data.Entities.Academic.NonEvaluableTaskGrade", "NonEvaluableTaskGrade")
                        .WithMany("NonEvaluableGradeReasons")
                        .HasForeignKey("NonEvaluableTaskGradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_NonEvaluableGradeReasons_NonEvaluableTaskGradeId");

                    b.Navigation("NonEvaluableTaskGrade");
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.NonEvaluableMissionRecord", b =>
                {
                    b.HasOne("SICAF.Data.Entities.Academic.Aircraft", "Aircraft")
                        .WithMany()
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_NonEvaluableMissionRecords_AircraftId");

                    b.HasOne("SICAF.Data.Entities.Academic.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_NonEvaluableMissionRecords_CourseId");

                    b.HasOne("SICAF.Data.Entities.Identity.User", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_NonEvaluableMissionRecords_InstructorId");

                    b.HasOne("SICAF.Data.Entities.Academic.Phase", "Phase")
                        .WithMany()
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_NonEvaluableMissionRecords_PhaseId");

                    b.HasOne("SICAF.Data.Entities.Identity.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_NonEvaluableMissionRecords_StudentId");

                    b.Navigation("Aircraft");

                    b.Navigation("Course");

                    b.Navigation("Instructor");

                    b.Navigation("Phase");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.NonEvaluableTaskGrade", b =>
                {
                    b.HasOne("SICAF.Data.Entities.Identity.User", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_NonEvaluableTaskGrades_InstructorId");

                    b.HasOne("SICAF.Data.Entities.Academic.NonEvaluableMissionRecord", "NonEvaluableMissionRecord")
                        .WithMany("NonEvaluableTaskGrades")
                        .HasForeignKey("NonEvaluableMissionRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_NonEvaluableTaskGrades_NonEvaluableMissionRecordId");

                    b.HasOne("SICAF.Data.Entities.Identity.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_NonEvaluableTaskGrades_StudentId");

                    b.HasOne("SICAF.Data.Entities.Academic.Tasks", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_NonEvaluableTaskGrades_TaskId");

                    b.Navigation("Instructor");

                    b.Navigation("NonEvaluableMissionRecord");

                    b.Navigation("Student");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.Phase", b =>
                {
                    b.HasOne("SICAF.Data.Entities.Academic.Phase", "PrerequisitePhase")
                        .WithMany("DependentPhases")
                        .HasForeignKey("PrerequisitePhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Phases_PrerequisitePhaseId");

                    b.Navigation("PrerequisitePhase");
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.StudentCommitteeRecord", b =>
                {
                    b.HasOne("SICAF.Data.Entities.Academic.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_StudentCommitteeRecords_CourseId");

                    b.HasOne("SICAF.Data.Entities.Identity.User", "RegisteredByLeader")
                        .WithMany()
                        .HasForeignKey("LeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_StudentCommitteeRecords_LeaderId");

                    b.HasOne("SICAF.Data.Entities.Academic.Phase", "Phase")
                        .WithMany()
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_StudentCommitteeRecords_PhaseId");

                    b.HasOne("SICAF.Data.Entities.Identity.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_StudentCommitteeRecords_StudentId");

                    b.Navigation("Course");

                    b.Navigation("Phase");

                    b.Navigation("RegisteredByLeader");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.StudentGradeNRedReason", b =>
                {
                    b.HasOne("SICAF.Data.Entities.Academic.StudentTaskGrade", "StudentTaskGrade")
                        .WithMany("StudentGradeNRedReasons")
                        .HasForeignKey("StudentTaskGradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_StudentGradeNRedReason_StudentTaskGradeId");

                    b.Navigation("StudentTaskGrade");
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.StudentMissionProgress", b =>
                {
                    b.HasOne("SICAF.Data.Entities.Academic.Aircraft", "Aircraft")
                        .WithMany()
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_StudentMissionProgress_AircraftId");

                    b.HasOne("SICAF.Data.Entities.Academic.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_StudentMissionProgress_CourseId");

                    b.HasOne("SICAF.Data.Entities.Identity.User", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_StudentMissionProgress_InstructorId");

                    b.HasOne("SICAF.Data.Entities.Academic.Mission", "Mission")
                        .WithMany("StudentMissionProgresses")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_StudentMissionProgress_MissionId");

                    b.HasOne("SICAF.Data.Entities.Academic.Phase", "Phase")
                        .WithMany()
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_StudentMissionProgress_PhaseId");

                    b.HasOne("SICAF.Data.Entities.Identity.User", "Student")
                        .WithMany("StudentMissionProgressesAsStudent")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_StudentMissionProgress_StudentId");

                    b.Navigation("Aircraft");

                    b.Navigation("Course");

                    b.Navigation("Instructor");

                    b.Navigation("Mission");

                    b.Navigation("Phase");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.StudentPhaseProgress", b =>
                {
                    b.HasOne("SICAF.Data.Entities.Academic.Course", "Course")
                        .WithMany("StudentPhaseProgresses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_StudentPhaseProgress_CourseId");

                    b.HasOne("SICAF.Data.Entities.Identity.User", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_StudentPhaseProgress_LeaderId");

                    b.HasOne("SICAF.Data.Entities.Academic.Phase", "Phase")
                        .WithMany("StudentPhaseProgresses")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_StudentPhaseProgress_PhaseId");

                    b.HasOne("SICAF.Data.Entities.Identity.User", "Student")
                        .WithMany("StudentPhaseProgresses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_StudentPhaseProgress_StudentId");

                    b.Navigation("Course");

                    b.Navigation("Leader");

                    b.Navigation("Phase");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.StudentTaskGrade", b =>
                {
                    b.HasOne("SICAF.Data.Entities.Identity.User", "Instructor")
                        .WithMany("StudentTaskGradesAsInstructor")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_StudentTaskGrades_InstructorId");

                    b.HasOne("SICAF.Data.Entities.Academic.Mission", "Mission")
                        .WithMany("StudentTaskGrades")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_StudentTaskGrades_MissionId");

                    b.HasOne("SICAF.Data.Entities.Identity.User", "Student")
                        .WithMany("StudentTaskGradesAsStudent")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_StudentTaskGrades_StudentId");

                    b.HasOne("SICAF.Data.Entities.Academic.StudentMissionProgress", "StudentMissionProgress")
                        .WithMany("StudentTaskGrades")
                        .HasForeignKey("StudentMissionProgressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_StudentTaskGrades_StudentMissionProgresId");

                    b.HasOne("SICAF.Data.Entities.Academic.Tasks", "Task")
                        .WithMany("StudentTaskGrades")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_StudentTaskGrades_TaskId");

                    b.Navigation("Instructor");

                    b.Navigation("Mission");

                    b.Navigation("Student");

                    b.Navigation("StudentMissionProgress");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.UserCourse", b =>
                {
                    b.HasOne("SICAF.Data.Entities.Academic.Course", "Course")
                        .WithMany("UserCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserCourses_CourseId");

                    b.HasOne("SICAF.Data.Entities.Identity.User", "User")
                        .WithMany("UserCourses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Users_UserId");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SICAF.Data.Entities.Identity.UserRole", b =>
                {
                    b.HasOne("SICAF.Data.Entities.Identity.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Roles");

                    b.HasOne("SICAF.Data.Entities.Identity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_UserId");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.Course", b =>
                {
                    b.Navigation("StudentPhaseProgresses");

                    b.Navigation("UserCourses");
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.Mission", b =>
                {
                    b.Navigation("FlightHourLogs");

                    b.Navigation("MissionTasks");

                    b.Navigation("StudentMissionProgresses");

                    b.Navigation("StudentTaskGrades");
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.NonEvaluableMissionRecord", b =>
                {
                    b.Navigation("NonEvaluableTaskGrades");
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.NonEvaluableTaskGrade", b =>
                {
                    b.Navigation("NonEvaluableGradeReasons");
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.Phase", b =>
                {
                    b.Navigation("DependentPhases");

                    b.Navigation("Missions");

                    b.Navigation("StudentPhaseProgresses");
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.StudentMissionProgress", b =>
                {
                    b.Navigation("StudentTaskGrades");
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.StudentTaskGrade", b =>
                {
                    b.Navigation("StudentGradeNRedReasons");
                });

            modelBuilder.Entity("SICAF.Data.Entities.Academic.Tasks", b =>
                {
                    b.Navigation("StudentTaskGrades");
                });

            modelBuilder.Entity("SICAF.Data.Entities.Identity.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SICAF.Data.Entities.Identity.User", b =>
                {
                    b.Navigation("AviationProfile");

                    b.Navigation("FlightHourLogs");

                    b.Navigation("StudentMissionProgressesAsStudent");

                    b.Navigation("StudentPhaseProgresses");

                    b.Navigation("StudentTaskGradesAsInstructor");

                    b.Navigation("StudentTaskGradesAsStudent");

                    b.Navigation("UserCourses");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
